---
- name: Install java and net-tools
  hosts: nexus
  become: true
  tasks:
    - name: Update apt repo and cashe
      become: true
      yum: 
        update_cache: yes

    - name: Install OpenJDK 8 JDK package
      yum:
        name: java-1.8.0-openjdk
        state: present
        update_cache: yes

    - name: Install net-tools
      become: true
      yum: 
        name: net-tools

- name: Download and Unpack Nexus installer
  hosts: nexus
  become: true
  tasks:
    - name: Check nexus folder status
      stat:
        path: /opt/nexus
      register: stat_result
    - debug: msg={{stat_result.stat.exists}}

    - name: Download Nexus
      get_url:
        url: "https://download.sonatype.com/nexus/3/latest-unix.tar.gz"
        dest: /opt/
      register: download_result
    - debug: msg={{download_result}}

    - name: Unpack Nexus
      unarchive:
        src: "{{download_result.dest}}"
        dest: /opt/
        remote_src: yes
      when: not stat_result.stat.exists

    - name: Find Nexus folder
      find:
        paths: /opt
        file_type: directory
        patterns: "nexus-*"
      register: find_result
    - debug: msg={{find_result}}

    - name: Rename Nexus folder
      when: not stat_result.stat.exists
      shell: mv {{find_result.files[0].path}} /opt/nexus

- name: Create nexus user to own nexus folder
  hosts: nexus
  become: true
  tasks:
    - name: Add nexus group
      group:
        name: nexus
        state: present

    - name: Create nexus user
      user:
        name: nexus
        group: nexus

    - name: Make nexus user owner of nexus folder
      file: 
        path: /opt/nexus
        owner: nexus
        group: nexus
        state: directory
        recurse: yes

    - name: Make nexus user owner of sonatype folder
      file: 
        path: /opt/sonatype-work
        owner: nexus
        group: nexus
        state: directory
        recurse: yes
    
- name: Start nexus with nexus user
  hosts: nexus
  become: true
  tasks:
    - name: Set run_as_user nexus
      lineinfile:
        path: /opt/nexus/bin/nexus.rc
        regexp: '^#run_as_user=""$'
        line: run_as_user="nexus"

- name: Start nexus
  hosts: nexus
  become: true
  become_user: nexus
  tasks:
    - name: Start nexus
      command: /opt/nexus/bin/nexus start

    - name: Ensure App is running
      shell: ps aux | grep node
      register: app_status
    - debug: msg={{app_status.stdout_lines}}

    - name: Wait 1 minute
      pause:
        minutes: 1
    - name: Check with netstat
      shell: netstat -plnt
      register: app_status
    - debug: msg={{app_status.stdout_lines}}