---
- name: Configure nginx web server
  hosts: ec2
  become: true
  tasks: 
    - name: install nginx server
      become: true
      yum:
        name: nginx  
        state: absent
    - name: start nginx server
      become: true
      service:
        name: nginx
        state: stopped